# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
