# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='colors',
            field=models.ManyToManyField(to='photos.Color'),
        ),
    ]
