# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170727_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='colors',
            new_name='color',
        ),
    ]
