# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20170727_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='colors',
        ),
        migrations.AddField(
            model_name='color',
            name='photos',
            field=models.ManyToManyField(to='photos.Photo'),
        ),
    ]
