# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20170727_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='colors',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
