# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20170727_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='colors',
        ),
        migrations.AddField(
            model_name='photo',
            name='color1',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='color2',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='color3',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
