# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20170727_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'no_username', max_length=30)),
                ('email', models.CharField(default=b'no_email', max_length=30)),
            ],
        ),
    ]
