# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20170802_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=b'no_password', max_length=30),
        ),
    ]
