# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_auto_20170803_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
